-- Generated by scripts/generate-db-seed.mjs from the bundled catalog v2 (the real 7-card catalog).
-- Local development only. This is an UNAPPROVED draft, with no reviewer or fabricated
-- issuer-text capture. It cannot publish until real source evidence is attached and
-- an authorized human explicitly reviews it. No users, sessions, or secrets are seeded.
insert into catalog_private.drafts(id,catalog)
values ('00000000-0000-4000-8000-000000000001', $catalog${
  "schemaVersion": 2,
  "version": "2026-09-29.real.1",
  "verifiedAt": "2026-09-29T00:00:00Z",
  "expiresAt": "2026-10-29T00:00:00Z",
  "merchants": [
    {
      "id": "best-buy-us",
      "name": "Best Buy",
      "onlineRetail": true,
      "physicalGoods": true,
      "usMerchant": true,
      "expectedCategory": "electronics",
      "mcc": {
        "code": "5732",
        "confidence": "low",
        "sourceIds": [
          "check-mcc-best-buy"
        ]
      },
      "notes": "MCC 5732 (electronics stores) comes from an undated community lookup only. Online orders qualify as online retail only when paid online; buy online, pick up in store counts only if Best Buy codes it as online. Geek Squad services and protection plans may count as services, not retail."
    },
    {
      "id": "newegg-us",
      "name": "Newegg",
      "onlineRetail": true,
      "physicalGoods": true,
      "usMerchant": true,
      "expectedCategory": "electronics",
      "mcc": {
        "code": "5732",
        "confidence": "low",
        "sourceIds": [
          "check-mcc-newegg"
        ]
      },
      "notes": "MCC 5732 (electronics stores) comes from an undated community lookup only. Newegg Marketplace third-party sellers may post differently; no evidence either way."
    },
    {
      "id": "amazon-us",
      "name": "Amazon",
      "onlineRetail": true,
      "physicalGoods": true,
      "usMerchant": true,
      "expectedCategory": "general-merchandise",
      "mcc": {
        "code": null,
        "confidence": "low",
        "sourceIds": []
      },
      "notes": "No MCC evidence was collected. American Express names Amazon.com as an eligible online retailer and says online superstores such as Amazon are not supermarkets. Items from third-party marketplace sellers may post differently; digital goods and services are not physical goods."
    }
  ],
  "sources": [
    {
      "id": "citi-double-cash-product",
      "title": "Citi Double Cash Card",
      "url": "https://www.citi.com/credit-cards/citi-double-cash-credit-card",
      "checkedOn": "2026-09-29"
    },
    {
      "id": "citi-double-cash-additional-info",
      "title": "Citi Double Cash Card: Additional Information",
      "url": "https://www.citi.com/credit-cards/citi-double-cash-credit-card/additional-information",
      "checkedOn": "2026-09-29"
    },
    {
      "id": "citi-double-cash-terms-pdf",
      "title": "Citi Double Cash ThankYou Terms and Conditions",
      "url": "https://www.citi.com/CRD/PDF/DoubleCashThankyouTC.pdf",
      "checkedOn": "2026-09-29"
    },
    {
      "id": "wells-fargo-active-cash-product",
      "title": "Wells Fargo Active Cash Card",
      "url": "https://creditcards.wellsfargo.com/active-cash-credit-card/",
      "checkedOn": "2026-09-29"
    },
    {
      "id": "chase-freedom-unlimited-product",
      "title": "Chase Freedom Unlimited",
      "url": "https://creditcards.chase.com/cash-back-credit-cards/freedom/unlimited",
      "checkedOn": "2026-09-29"
    },
    {
      "id": "chase-rewards-category-faq",
      "title": "Chase Rewards Category FAQ",
      "url": "https://www.chase.com/personal/credit-cards/rewards-category-faq",
      "checkedOn": "2026-09-29"
    },
    {
      "id": "capital-one-quicksilver-product",
      "title": "Capital One Quicksilver",
      "url": "https://www.capitalone.com/credit-cards/quicksilver/",
      "checkedOn": "2026-09-29"
    },
    {
      "id": "capital-one-quicksilver-terms",
      "title": "Capital One Quicksilver: Important Disclosures and Rewards Terms",
      "url": "https://disclosures.capitalone.com/disclosure.40671.en-US.html",
      "checkedOn": "2026-09-29"
    },
    {
      "id": "capital-one-savor-product",
      "title": "Capital One Savor",
      "url": "https://www.capitalone.com/credit-cards/savor/",
      "checkedOn": "2026-09-29"
    },
    {
      "id": "capital-one-savor-terms",
      "title": "Capital One Savor: Important Disclosures and Rewards Terms",
      "url": "https://disclosures.capitalone.com/disclosure.40679.en-US.html",
      "checkedOn": "2026-09-29"
    },
    {
      "id": "amex-blue-cash-everyday-product",
      "title": "Blue Cash Everyday Card",
      "url": "https://www.americanexpress.com/us/credit-cards/card/blue-cash-everyday/",
      "checkedOn": "2026-09-29"
    },
    {
      "id": "amex-blue-cash-everyday-terms",
      "title": "Blue Cash Everyday Card: Offer and Benefit Terms",
      "url": "https://www.americanexpress.com/us/credit-cards/card-application/apply/prospect/terms/blue-cash-everyday-credit-card/25330-10-0",
      "checkedOn": "2026-09-29"
    },
    {
      "id": "amex-blue-cash-preferred-product",
      "title": "Blue Cash Preferred Card",
      "url": "https://www.americanexpress.com/us/credit-cards/card/blue-cash-preferred/",
      "checkedOn": "2026-09-29"
    },
    {
      "id": "amex-blue-cash-preferred-terms",
      "title": "Blue Cash Preferred Card: Offer and Benefit Terms",
      "url": "https://www.americanexpress.com/us/credit-cards/card-application/apply/prospect/terms/blue-cash-preferred-credit-card/25330-10-0",
      "checkedOn": "2026-09-29"
    },
    {
      "id": "amex-rewards-info-retail",
      "title": "American Express Rewards Info: Retail Categories",
      "url": "https://www.americanexpress.com/us/rewards-info/retail.html",
      "checkedOn": "2026-09-29"
    },
    {
      "id": "check-mcc-best-buy",
      "title": "CheckMCC: Best Buy (community MCC lookup, undated)",
      "url": "https://check-mcc.com/merchant/best-buy",
      "checkedOn": "2026-09-28"
    },
    {
      "id": "check-mcc-newegg",
      "title": "CheckMCC: Newegg (community MCC lookup, undated)",
      "url": "https://check-mcc.com/merchant/newegg",
      "checkedOn": "2026-09-28"
    }
  ],
  "cards": [
    {
      "id": "citi-double-cash",
      "name": "Citi Double Cash",
      "shortName": "Double Cash",
      "issuer": "Citi",
      "rewardCurrency": "points",
      "pointValueHundredthsOfCent": 100,
      "rules": [
        {
          "id": "double-cash-base",
          "category": "all-purchases",
          "issuerWording": "every purchase",
          "rateBps": 200,
          "paidOnPaymentBps": 100,
          "cap": {
            "kind": "none"
          },
          "activation": "none",
          "usMerchantsOnly": false,
          "excludedPaymentPaths": [],
          "limitedTime": null,
          "sourceIds": [
            "citi-double-cash-product",
            "citi-double-cash-additional-info",
            "citi-double-cash-terms-pdf"
          ]
        },
        {
          "id": "double-cash-travel-portal",
          "category": "travel-portal",
          "issuerWording": "hotels, car rentals, and attractions booked through the Citi Travel® portal",
          "rateBps": 500,
          "paidOnPaymentBps": 100,
          "cap": {
            "kind": "none"
          },
          "activation": "none",
          "usMerchantsOnly": false,
          "excludedPaymentPaths": [],
          "limitedTime": null,
          "sourceIds": [
            "citi-double-cash-product",
            "citi-double-cash-additional-info",
            "citi-double-cash-terms-pdf"
          ]
        }
      ],
      "exclusions": [
        "Balance transfers, cash advances, cash-like transactions, gift card and prepaid loads, person-to-person payments, and account fees"
      ]
    },
    {
      "id": "wells-fargo-active-cash",
      "name": "Wells Fargo Active Cash",
      "shortName": "Active Cash",
      "issuer": "Wells Fargo",
      "rewardCurrency": "cash-back",
      "pointValueHundredthsOfCent": null,
      "rules": [
        {
          "id": "active-cash-base",
          "category": "all-purchases",
          "issuerWording": "purchases",
          "rateBps": 200,
          "paidOnPaymentBps": 0,
          "cap": {
            "kind": "none"
          },
          "activation": "none",
          "usMerchantsOnly": false,
          "excludedPaymentPaths": [],
          "limitedTime": null,
          "sourceIds": [
            "wells-fargo-active-cash-product"
          ]
        }
      ],
      "exclusions": [
        "Cash advances, cash equivalents, and balance transfers"
      ]
    },
    {
      "id": "capital-one-quicksilver",
      "name": "Capital One Quicksilver",
      "shortName": "Quicksilver",
      "issuer": "Capital One",
      "rewardCurrency": "cash-back",
      "pointValueHundredthsOfCent": null,
      "rules": [
        {
          "id": "quicksilver-base",
          "category": "all-purchases",
          "issuerWording": "all other purchases",
          "rateBps": 150,
          "paidOnPaymentBps": 0,
          "cap": {
            "kind": "none"
          },
          "activation": "unstated",
          "usMerchantsOnly": false,
          "excludedPaymentPaths": [],
          "limitedTime": null,
          "sourceIds": [
            "capital-one-quicksilver-product",
            "capital-one-quicksilver-terms"
          ]
        },
        {
          "id": "quicksilver-travel-portal",
          "category": "travel-portal",
          "issuerWording": "hotels, vacation rentals and rental cars booked through Capital One Travel",
          "rateBps": 500,
          "paidOnPaymentBps": 0,
          "cap": {
            "kind": "none"
          },
          "activation": "unstated",
          "usMerchantsOnly": false,
          "excludedPaymentPaths": [],
          "limitedTime": null,
          "sourceIds": [
            "capital-one-quicksilver-product",
            "capital-one-quicksilver-terms"
          ]
        },
        {
          "id": "quicksilver-entertainment-portal",
          "category": "entertainment-portal",
          "issuerWording": "Capital One Entertainment purchases",
          "rateBps": 500,
          "paidOnPaymentBps": 0,
          "cap": {
            "kind": "none"
          },
          "activation": "unstated",
          "usMerchantsOnly": false,
          "excludedPaymentPaths": [],
          "limitedTime": null,
          "sourceIds": [
            "capital-one-quicksilver-product",
            "capital-one-quicksilver-terms"
          ]
        }
      ],
      "exclusions": [
        "Cash advances, balance transfers, and checks used to access your account"
      ]
    },
    {
      "id": "capital-one-savor",
      "name": "Capital One Savor",
      "shortName": "Savor",
      "issuer": "Capital One",
      "rewardCurrency": "cash-back",
      "pointValueHundredthsOfCent": null,
      "rules": [
        {
          "id": "savor-base",
          "category": "all-purchases",
          "issuerWording": "all other purchases",
          "rateBps": 100,
          "paidOnPaymentBps": 0,
          "cap": {
            "kind": "none"
          },
          "activation": "unstated",
          "usMerchantsOnly": false,
          "excludedPaymentPaths": [],
          "limitedTime": null,
          "sourceIds": [
            "capital-one-savor-product",
            "capital-one-savor-terms"
          ]
        },
        {
          "id": "savor-entertainment-portal",
          "category": "entertainment-portal",
          "issuerWording": "Capital One Entertainment purchases",
          "rateBps": 800,
          "paidOnPaymentBps": 0,
          "cap": {
            "kind": "none"
          },
          "activation": "unstated",
          "usMerchantsOnly": false,
          "excludedPaymentPaths": [],
          "limitedTime": null,
          "sourceIds": [
            "capital-one-savor-product",
            "capital-one-savor-terms"
          ]
        },
        {
          "id": "savor-travel-portal",
          "category": "travel-portal",
          "issuerWording": "hotels, vacation rentals and rental cars booked through Capital One Travel",
          "rateBps": 500,
          "paidOnPaymentBps": 0,
          "cap": {
            "kind": "none"
          },
          "activation": "unstated",
          "usMerchantsOnly": false,
          "excludedPaymentPaths": [],
          "limitedTime": null,
          "sourceIds": [
            "capital-one-savor-product",
            "capital-one-savor-terms"
          ]
        },
        {
          "id": "savor-dining",
          "category": "dining",
          "issuerWording": "dining",
          "rateBps": 300,
          "paidOnPaymentBps": 0,
          "cap": {
            "kind": "none"
          },
          "activation": "unstated",
          "usMerchantsOnly": false,
          "excludedPaymentPaths": [],
          "limitedTime": null,
          "sourceIds": [
            "capital-one-savor-product",
            "capital-one-savor-terms"
          ]
        },
        {
          "id": "savor-entertainment",
          "category": "entertainment",
          "issuerWording": "qualified entertainment purchases",
          "rateBps": 300,
          "paidOnPaymentBps": 0,
          "cap": {
            "kind": "none"
          },
          "activation": "unstated",
          "usMerchantsOnly": false,
          "excludedPaymentPaths": [],
          "limitedTime": null,
          "sourceIds": [
            "capital-one-savor-product",
            "capital-one-savor-terms"
          ]
        },
        {
          "id": "savor-streaming",
          "category": "streaming",
          "issuerWording": "popular streaming services",
          "rateBps": 300,
          "paidOnPaymentBps": 0,
          "cap": {
            "kind": "none"
          },
          "activation": "unstated",
          "usMerchantsOnly": false,
          "excludedPaymentPaths": [],
          "limitedTime": null,
          "sourceIds": [
            "capital-one-savor-product",
            "capital-one-savor-terms"
          ]
        },
        {
          "id": "savor-supermarkets",
          "category": "supermarkets",
          "issuerWording": "purchases made at grocery stores",
          "rateBps": 300,
          "paidOnPaymentBps": 0,
          "cap": {
            "kind": "none"
          },
          "activation": "unstated",
          "usMerchantsOnly": false,
          "excludedPaymentPaths": [],
          "limitedTime": null,
          "sourceIds": [
            "capital-one-savor-product",
            "capital-one-savor-terms"
          ]
        }
      ],
      "exclusions": [
        "Cash advances, balance transfers, and checks used to access your account"
      ]
    },
    {
      "id": "chase-freedom-unlimited",
      "name": "Chase Freedom Unlimited",
      "shortName": "Freedom Unlimited",
      "issuer": "Chase",
      "rewardCurrency": "cash-back",
      "pointValueHundredthsOfCent": null,
      "rules": [
        {
          "id": "freedom-unlimited-base",
          "category": "all-purchases",
          "issuerWording": "all other purchases",
          "rateBps": 150,
          "paidOnPaymentBps": 0,
          "cap": {
            "kind": "none"
          },
          "activation": "unstated",
          "usMerchantsOnly": false,
          "excludedPaymentPaths": [],
          "limitedTime": null,
          "sourceIds": [
            "chase-freedom-unlimited-product",
            "chase-rewards-category-faq"
          ]
        },
        {
          "id": "freedom-unlimited-travel-portal",
          "category": "travel-portal",
          "issuerWording": "travel purchased through Chase Travel",
          "rateBps": 500,
          "paidOnPaymentBps": 0,
          "cap": {
            "kind": "unstated"
          },
          "activation": "unstated",
          "usMerchantsOnly": false,
          "excludedPaymentPaths": [],
          "limitedTime": null,
          "sourceIds": [
            "chase-freedom-unlimited-product",
            "chase-rewards-category-faq"
          ]
        },
        {
          "id": "freedom-unlimited-dining",
          "category": "dining",
          "issuerWording": "dining at restaurants, including takeout and eligible delivery services",
          "rateBps": 300,
          "paidOnPaymentBps": 0,
          "cap": {
            "kind": "unstated"
          },
          "activation": "unstated",
          "usMerchantsOnly": false,
          "excludedPaymentPaths": [],
          "limitedTime": null,
          "sourceIds": [
            "chase-freedom-unlimited-product",
            "chase-rewards-category-faq"
          ]
        },
        {
          "id": "freedom-unlimited-drugstores",
          "category": "drugstores",
          "issuerWording": "drugstore purchases",
          "rateBps": 300,
          "paidOnPaymentBps": 0,
          "cap": {
            "kind": "unstated"
          },
          "activation": "unstated",
          "usMerchantsOnly": false,
          "excludedPaymentPaths": [],
          "limitedTime": null,
          "sourceIds": [
            "chase-freedom-unlimited-product",
            "chase-rewards-category-faq"
          ]
        }
      ],
      "exclusions": []
    },
    {
      "id": "amex-blue-cash-everyday",
      "name": "American Express Blue Cash Everyday",
      "shortName": "Blue Cash Everyday",
      "issuer": "American Express",
      "rewardCurrency": "cash-back",
      "pointValueHundredthsOfCent": null,
      "rules": [
        {
          "id": "bce-base",
          "category": "all-purchases",
          "issuerWording": "all other eligible purchases",
          "rateBps": 100,
          "paidOnPaymentBps": 0,
          "cap": {
            "kind": "unstated"
          },
          "activation": "unstated",
          "usMerchantsOnly": false,
          "excludedPaymentPaths": [],
          "limitedTime": null,
          "sourceIds": [
            "amex-blue-cash-everyday-product",
            "amex-blue-cash-everyday-terms",
            "amex-rewards-info-retail"
          ]
        },
        {
          "id": "bce-supermarkets",
          "category": "supermarkets",
          "issuerWording": "supermarkets located in the U.S.",
          "rateBps": 300,
          "paidOnPaymentBps": 0,
          "cap": {
            "kind": "spend",
            "amountCents": 600000,
            "period": "calendar-year",
            "rateAfterCapBps": 100
          },
          "activation": "unstated",
          "usMerchantsOnly": true,
          "excludedPaymentPaths": [],
          "limitedTime": null,
          "sourceIds": [
            "amex-blue-cash-everyday-product",
            "amex-blue-cash-everyday-terms",
            "amex-rewards-info-retail"
          ]
        },
        {
          "id": "bce-online-retail",
          "category": "online-retail",
          "issuerWording": "U.S. online retail purchases",
          "rateBps": 300,
          "paidOnPaymentBps": 0,
          "cap": {
            "kind": "spend",
            "amountCents": 600000,
            "period": "year-unspecified",
            "rateAfterCapBps": 100
          },
          "activation": "unstated",
          "usMerchantsOnly": true,
          "excludedPaymentPaths": [
            "bnpl"
          ],
          "limitedTime": null,
          "sourceIds": [
            "amex-blue-cash-everyday-product",
            "amex-blue-cash-everyday-terms",
            "amex-rewards-info-retail"
          ]
        },
        {
          "id": "bce-gas",
          "category": "gas",
          "issuerWording": "gasoline at gas stations located in the U.S",
          "rateBps": 300,
          "paidOnPaymentBps": 0,
          "cap": {
            "kind": "spend",
            "amountCents": 600000,
            "period": "year-unspecified",
            "rateAfterCapBps": 100
          },
          "activation": "unstated",
          "usMerchantsOnly": true,
          "excludedPaymentPaths": [],
          "limitedTime": null,
          "sourceIds": [
            "amex-blue-cash-everyday-product",
            "amex-blue-cash-everyday-terms",
            "amex-rewards-info-retail"
          ]
        }
      ],
      "exclusions": [
        "Fees, interest, balance transfers, cash advances, travelers checks, prepaid cards, gift cards, person-to-person transactions, and other cash equivalents"
      ]
    },
    {
      "id": "amex-blue-cash-preferred",
      "name": "American Express Blue Cash Preferred",
      "shortName": "Blue Cash Preferred",
      "issuer": "American Express",
      "rewardCurrency": "cash-back",
      "pointValueHundredthsOfCent": null,
      "rules": [
        {
          "id": "bcp-base",
          "category": "all-purchases",
          "issuerWording": "all other eligible purchases",
          "rateBps": 100,
          "paidOnPaymentBps": 0,
          "cap": {
            "kind": "unstated"
          },
          "activation": "unstated",
          "usMerchantsOnly": false,
          "excludedPaymentPaths": [],
          "limitedTime": null,
          "sourceIds": [
            "amex-blue-cash-preferred-product",
            "amex-blue-cash-preferred-terms",
            "amex-rewards-info-retail"
          ]
        },
        {
          "id": "bcp-supermarkets",
          "category": "supermarkets",
          "issuerWording": "supermarkets located in the U.S.",
          "rateBps": 600,
          "paidOnPaymentBps": 0,
          "cap": {
            "kind": "spend",
            "amountCents": 600000,
            "period": "calendar-year",
            "rateAfterCapBps": 100
          },
          "activation": "unstated",
          "usMerchantsOnly": true,
          "excludedPaymentPaths": [],
          "limitedTime": null,
          "sourceIds": [
            "amex-blue-cash-preferred-product",
            "amex-blue-cash-preferred-terms",
            "amex-rewards-info-retail"
          ]
        },
        {
          "id": "bcp-streaming",
          "category": "streaming",
          "issuerWording": "U.S. streaming subscriptions from select providers",
          "rateBps": 600,
          "paidOnPaymentBps": 0,
          "cap": {
            "kind": "unstated"
          },
          "activation": "unstated",
          "usMerchantsOnly": true,
          "excludedPaymentPaths": [],
          "limitedTime": null,
          "sourceIds": [
            "amex-blue-cash-preferred-product",
            "amex-blue-cash-preferred-terms",
            "amex-rewards-info-retail"
          ]
        },
        {
          "id": "bcp-transit",
          "category": "transit",
          "issuerWording": "transit",
          "rateBps": 300,
          "paidOnPaymentBps": 0,
          "cap": {
            "kind": "unstated"
          },
          "activation": "unstated",
          "usMerchantsOnly": false,
          "excludedPaymentPaths": [],
          "limitedTime": null,
          "sourceIds": [
            "amex-blue-cash-preferred-product",
            "amex-blue-cash-preferred-terms",
            "amex-rewards-info-retail"
          ]
        },
        {
          "id": "bcp-gas",
          "category": "gas",
          "issuerWording": "gasoline at gas stations located in the U.S.",
          "rateBps": 300,
          "paidOnPaymentBps": 0,
          "cap": {
            "kind": "unstated"
          },
          "activation": "unstated",
          "usMerchantsOnly": true,
          "excludedPaymentPaths": [],
          "limitedTime": null,
          "sourceIds": [
            "amex-blue-cash-preferred-product",
            "amex-blue-cash-preferred-terms",
            "amex-rewards-info-retail"
          ]
        }
      ],
      "exclusions": [
        "Fees, interest, balance transfers, cash advances, travelers checks, prepaid cards, gift cards, person-to-person transactions, and other cash equivalents"
      ]
    }
  ]
}$catalog$::jsonb)
on conflict (id) do nothing;
