-- Generated by scripts/generate-db-seed.mjs from the bundled pilot catalog.
-- Local development only. This is an UNAPPROVED draft, with no reviewer or fabricated
-- issuer-text capture. It cannot publish until real source evidence is attached and
-- an authorized human explicitly reviews it. No users, sessions, or secrets are seeded.
insert into catalog_private.drafts(id,catalog)
values ('00000000-0000-4000-8000-000000000001', $catalog${
  "schemaVersion": 1,
  "version": "2026-09-25.pilot.2",
  "verifiedAt": "2026-09-25T00:00:00Z",
  "expiresAt": "2026-10-25T00:00:00Z",
  "merchantIds": [
    "best-buy-us",
    "newegg-us"
  ],
  "sources": [
    {
      "id": "capital-one-quicksilver-benefits",
      "title": "Capital One Quicksilver benefits",
      "url": "https://www.capitalone.com/learn-grow/money-management/quicksilver-card-benefits/",
      "checkedOn": "2026-09-25"
    },
    {
      "id": "amex-bce-rewards",
      "title": "American Express Blue Cash Everyday rewards terms",
      "url": "https://global.americanexpress.com/card-benefits/terms/blue-cash-everyday",
      "checkedOn": "2026-09-25"
    },
    {
      "id": "amex-online-retail",
      "title": "American Express online retail category guidance",
      "url": "https://www.americanexpress.com/us/rewards-info/retail.htm",
      "checkedOn": "2026-09-25"
    }
  ],
  "cards": [
    {
      "id": "capital-one-quicksilver",
      "name": "Capital One Quicksilver",
      "shortName": "Quicksilver",
      "rules": [
        {
          "id": "quicksilver-base",
          "category": "all-eligible",
          "rateBps": 150,
          "requiresActivation": false,
          "sourceIds": [
            "capital-one-quicksilver-benefits"
          ]
        }
      ]
    },
    {
      "id": "amex-blue-cash-everyday",
      "name": "American Express Blue Cash Everyday",
      "shortName": "Blue Cash Everyday",
      "rules": [
        {
          "id": "bce-base",
          "category": "all-eligible",
          "rateBps": 100,
          "requiresActivation": false,
          "sourceIds": [
            "amex-bce-rewards"
          ]
        },
        {
          "id": "bce-online-retail",
          "category": "us-online-retail",
          "rateBps": 300,
          "annualCapCents": 600000,
          "requiresActivation": false,
          "sourceIds": [
            "amex-bce-rewards",
            "amex-online-retail"
          ]
        }
      ]
    }
  ]
}$catalog$::jsonb)
on conflict (id) do nothing;
