// Copies the Flight icons we use (MPL-2.0) into src/icons.generated.ts as path data, so each
// app bundles only these icons and renders them as inline SVG (no sprite, no remote asset).
// Usage: node scripts/generate-icons.mjs [--check]
import { readFileSync, writeFileSync } from 'node:fs';
import { createRequire } from 'node:module';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { format, resolveConfig } from 'prettier';

// Name → sizes. Add an icon here, then rerun the script.
const ICONS = {
  'alert-circle': [16, 24],
  'alert-diamond': [16, 24],
  'alert-triangle': [16, 24],
  'arrow-down': [16],
  'arrow-right': [16],
  'arrow-up': [16],
  check: [16],
  'check-circle': [16, 24],
  'chevron-down': [16],
  'chevron-right': [16],
  'chevron-up': [16],
  'credit-card': [16, 24],
  'external-link': [16],
  help: [16, 24],
  info: [16, 24],
  loading: [16, 24],
  lock: [16, 24],
  plus: [16],
  search: [16, 24],
  'shopping-cart': [16, 24],
  'swap-vertical': [16],
  trash: [16],
  x: [16],
};

const root = dirname(dirname(fileURLToPath(import.meta.url)));
const require = createRequire(import.meta.url);
const iconDir = join(dirname(require.resolve('@hashicorp/flight-icons/package.json')), 'svg');
const out = join(root, 'src', 'icons.generated.ts');

function attr(tag, name) {
  return new RegExp(`\\s${name}="([^"]*)"`).exec(tag)?.[1];
}

function parse(name, size) {
  const svg = readFileSync(join(iconDir, `${name}-${size}.svg`), 'utf8');
  if (attr(svg, 'viewBox') !== `0 0 ${size} ${size}`) throw new Error(`${name}-${size}: unexpected viewBox`);
  const group = /<g\s[^>]*>/.exec(svg)?.[0] ?? '';
  const groupRule = attr(group, 'fill-rule');
  const paths = [...svg.matchAll(/<path\s[^>]*\/>/g)].map(([tag]) => {
    const path = { d: attr(tag, 'd') };
    const opacity = attr(tag, 'opacity');
    const rule = attr(tag, 'fill-rule') ?? groupRule;
    if (!path.d) throw new Error(`${name}-${size}: path without d`);
    if (opacity) path.opacity = Number(opacity);
    if (rule) path.fillRule = rule;
    return path;
  });
  if (/<(circle|rect|ellipse|polygon|line|polyline|use|mask|defs)\b/.test(svg) || !paths.length)
    throw new Error(`${name}-${size}: unsupported SVG element; extend the generator`);
  return paths;
}

const lines = [
  '// Generated by scripts/generate-icons.mjs from @hashicorp/flight-icons (MPL-2.0). Do not edit.',
  `export type IconName = ${Object.keys(ICONS)
    .map((name) => `'${name}'`)
    .join(' | ')};`,
  "export type IconPath = { d: string; opacity?: number; fillRule?: 'evenodd' | 'nonzero' };",
  '',
  'export const FLIGHT_ICONS: Record<IconName, { 16: IconPath[]; 24?: IconPath[] }> = {',
];
for (const [name, sizes] of Object.entries(ICONS)) {
  lines.push(`  '${name}': {`);
  for (const size of sizes) lines.push(`    ${size}: ${JSON.stringify(parse(name, size))},`);
  lines.push('  },');
}
lines.push('};', '');
const text = await format(lines.join('\n'), { ...(await resolveConfig(out)), filepath: out });

if (process.argv.includes('--check')) {
  if (readFileSync(out, 'utf8') !== text) {
    console.error('src/icons.generated.ts is stale; run npm run icons --workspace=@ai-checkout/ui');
    process.exit(1);
  }
} else writeFileSync(out, text);
