import { readFile, writeFile } from 'node:fs/promises';
import { CATALOG_V3 } from '../packages/rewards-core/src/catalog-v3.ts';

const path = new URL('../supabase/seed.sql', import.meta.url);
const payload = JSON.stringify(CATALOG_V3, null, 2);
if (payload.includes('$catalog$')) throw new Error('Reserved seed delimiter in catalog');
const sql = `-- Generated by scripts/generate-db-seed.mjs from the bundled catalog v3 (CATALOG_V3, the 178-card catalog).
-- Local development only. This is an UNAPPROVED draft, with no reviewer or fabricated
-- issuer-text capture. It cannot publish until real source evidence is attached and
-- an authorized human explicitly reviews it. No users, sessions, or secrets are seeded.
insert into catalog_private.drafts(id,catalog)
values ('00000000-0000-4000-8000-000000000001', $catalog$${payload}$catalog$::jsonb)
on conflict (id) do nothing;
`;
if (process.argv.includes('--check')) {
  if ((await readFile(path, 'utf8')) !== sql)
    throw new Error('Database seed is out of date. Run npm run db:seed:generate.');
  console.log('Database seed matches the bundled catalog.');
} else {
  await writeFile(path, sql);
  console.log('Wrote the local unapproved catalog v3 draft seed.');
}
